apiVersion: v1
kind: Service
metadata:
  name: {{ include "yamo.fullname" . }}-webhook-service
  labels:
  {{- include "yamo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "yamo.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
