apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer       # becomes yamo-selfsigned-issuer after namePrefix
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert            # becomes yamo-serving-cert after namePrefix
  namespace: system
spec:
  dnsNames:
    - yamo-webhook-service.yamo-system.svc
    - yamo-webhook-service.yamo-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: yamo-selfsigned-issuer
  secretName: webhook-server-cert
