apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer       # becomes mysql-operator-selfsigned-issuer after namePrefix
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert            # becomes mysql-operator-serving-cert after namePrefix
  namespace: system
spec:
  dnsNames:
    - mysql-operator-webhook-service.mysql-operator-system.svc
    - mysql-operator-webhook-service.mysql-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: mysql-operator-selfsigned-issuer
  secretName: webhook-server-cert
